### ISSUE TITLE
Relation `get` method can't take `options`

### ISSUE THREAD

**Issue by xevix** [lostisland/sawyer#45] opened 2016-08-05 02:03 UTC
## Description

Unlike every other HTTP verb, `get` takes `data` but not `options`. Although named `options` in the method listed below, when passed to `call` this is interpreted as `data`. This means that you can't set custom headers or anything else from a `Relation`.

https://github.com/lostisland/sawyer/blob/master/lib/sawyer/relation.rb#L160

Given that the comment above the method shows both `data` and `options` this might just be an innocent copy+paste issue. If so, please let me know and I'll issue a PR.
## Workaround

Until fixed, just call the `call` method directly.

``` ruby
# GET params as first hash, method and headers as second hash.
rel.call({get_param: "value"}, {method: :get, headers: {accept: 'application/json'}}).data
```

**Comment by technoweenie** [comment] 2019-05-01 16:24
Closing this, as it's not a bug. GET/HEAD requests typically have no request body, so the methods on `Sawyer::Relation` only take the `options` argument. I've updated the tests in #62 to show this.

In your example, it looks like you're trying to set a query parameter, and not the request body. You should be able to do that with:

```ruby
rel.get(query: { get_param: 'value' }, headers: { accept: 'application/json' }).data
```

Of course, you can always use `#call` to send a GET request body.

**Closed by technoweenie** 2019-05-01 16:24 UTC
